spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/spring_demo
    username: root
    password: Stunning.0093
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  error:
    include-message: always